# ---------------------- 【每日数据录入区】（原有数据不变）----------------------
DAILY_DATA = [
    # 本周六（2025-11-22）：主持人李韫
    {"date_str": "2025-11-22", "member": "陈庚", "is_participate": 1, "host": "李韫", "review": ""},
    {"date_str": "2025-11-22", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "自由之花", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "Echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "李韫", "is_participate": 1, "host": "", "review": ""},  # 主持人自身也在参与列表
    # 本周五（2025-11-21）：主持人小妮
    {"date_str": "2025-11-21", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-21", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    # 本周四（2025-11-20）：主持人小马哥
    {"date_str": "2025-11-20", "member": "陈庚", "is_participate": 1, "host": "小马哥", "review": ""},
    {"date_str": "2025-11-20", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "Echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    # 本周三（2025-11-19）：主持人浅夏
    {"date_str": "2025-11-19", "member": "光影", "is_participate": 1, "host": "浅夏", "review": ""},
    {"date_str": "2025-11-19", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "Echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    # 本周二（2025-11-18）：主持人光影
    {"date_str": "2025-11-18", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-18", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    # 本周一（2025-11-17）：主持人时成成
    {"date_str": "2025-11-17", "member": "光影", "is_participate": 1, "host": "时成成", "review": ""},
    {"date_str": "2025-11-17", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "Echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "小妮", "is_participate": 1, "host": "", "review": ""},

    # 11月16日（周日）：主持人光影
    {"date_str": "2025-11-16", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-16", "member": "桃子", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "王永涛", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "鱼大爷", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},

    # 11月15日（周六）：主持人阳州
    {"date_str": "2025-11-15", "member": "鱼鱼", "is_participate": 1, "host": "阳州", "review": ""},
    {"date_str": "2025-11-15", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "光影", "is_participate": 1, "host": "", "review": ""},

    # 11月14日（周五）：主持人miss恩
    {"date_str": "2025-11-14", "member": "光影", "is_participate": 1, "host": "miss恩", "review": ""},
    {"date_str": "2025-11-14", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月13日（周四）：主持人小马哥
    {"date_str": "2025-11-13", "member": "光影", "is_participate": 1, "host": "小马哥", "review": ""},
    {"date_str": "2025-11-13", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "团子", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "小金", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月12日（周三）：主持人花满天
    {"date_str": "2025-11-12", "member": "光影", "is_participate": 1, "host": "花满天", "review": ""},
    {"date_str": "2025-11-12", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月11日（周二）：主持人光影
    {"date_str": "2025-11-11", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-11", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11月10日（周一）：主持人小妮
    {"date_str": "2025-11-10", "member": "阿成", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-10", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "阿童", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "曾律师", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},

# 1号（2025-11-01）：主持人小妮
    {"date_str": "2025-11-01", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-01", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 2号（2025-11-02）：主持人小妮
    {"date_str": "2025-11-02", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-02", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "Betty", "is_participate": 1, "host": "", "review": ""},

    # 3号（2025-11-03）：主持人光影
    {"date_str": "2025-11-03", "member": "莫非", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-03", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "阿童", "is_participate": 1, "host": "", "review": ""},

    # 4号（2025-11-04）：主持人小妮
    {"date_str": "2025-11-04", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-04", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "李韫", "is_participate": 1, "host": "", "review": ""},

    # 5号（2025-11-05）：主持人小妮
    {"date_str": "2025-11-05", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-05", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},

    # 6号（2025-11-06）：主持人小妮
    {"date_str": "2025-11-06", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-06", "member": "桃桃", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},

    # 7号（2025-11-07）：主持人光影
    {"date_str": "2025-11-07", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-07", "member": "小妍", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "桃桃", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "小金", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},

    # 8号（2025-11-08）：主持人小妮
    {"date_str": "2025-11-08", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-08", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},

    # 9号（2025-11-09）：主持人光影
    {"date_str": "2025-11-09", "member": "Betty", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-09", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "白了个白", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "自由之花", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阿信", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "九月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11-09（主持人光影）
    {"date_str": "2025-11-09", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-09", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "九月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "Isa", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "Betty", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小金", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11-16（主持人光影）
    {"date_str": "2025-11-16", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-16", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "Betty", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "九月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "Isa", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小妮", "is_participate": 1, "host": "", "review": ""},

    {"date_str": "2025-11-01", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "平平", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "平平", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "平平", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "桃子", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "Echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "夏天", "is_participate": 1, "host": "", "review": ""},

    # 11-23（主持人miss恩）
    {"date_str": "2025-11-23", "member": "miss恩", "is_participate": 1, "host": "miss恩", "review": ""},
    {"date_str": "2025-11-23", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},

    # 11月24日（主持人：小妮）
    {"date_str": "2025-11-24", "member": "小妮", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-24", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月25日（主持人：阿成）
    {"date_str": "2025-11-25", "member": "阿成", "is_participate": 1, "host": "阿成", "review": ""},
    {"date_str": "2025-11-25", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-25", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-25", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-25", "member": "七公主", "is_participate": 1, "host": "", "review": ""},

    # 11月26日（主持人：光影）
    {"date_str": "2025-11-26", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-26", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11月27日（主持人：鱼鱼）
    {"date_str": "2025-11-27", "member": "鱼鱼", "is_participate": 1, "host": "鱼鱼", "review": ""},
    {"date_str": "2025-11-27", "member": "阿童", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "晴天", "is_participate": 1, "host": "", "review": ""},

    # 11月28日（主持人：小马哥）
    {"date_str": "2025-11-28", "member": "小马哥", "is_participate": 1, "host": "小马哥", "review": ""},
    {"date_str": "2025-11-28", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "阳州", "is_participate": 1, "host": "", "review": ""},

    # 11月29日（主持人：阳州）
    {"date_str": "2025-11-29", "member": "阳州", "is_participate": 1, "host": "阳州", "review": ""},
    {"date_str": "2025-11-29", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "自由之花", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "夏天", "is_participate": 1, "host": "", "review": ""},

    # 11月30日（主持人：匆匆）
    {"date_str": "2025-11-30", "member": "匆匆", "is_participate": 1, "host": "匆匆", "review": ""},
    {"date_str": "2025-11-30", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "阿童", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "七公主", "is_participate": 1, "host": "", "review": ""},

    {"date_str": "2025-12-01", "member": "阿童", "is_participate": 1, "host": "阿童", "review": ""},
    {"date_str": "2025-12-01", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-12-01", "member": "李韫", "is_participate": 1, "host": "", "review": "在陌生环境中营造安全感高效写作1小时；反思需提升饮食健康，今日计划去健身房。"},
    {"date_str": "2025-12-01", "member": "小马哥", "is_participate": 1, "host": "", "review": "参加师傅线下学习，复习上周内容并聆听修行分享；领悟'福不可尽享'，推掉两场活动专注学习。"},
    {"date_str": "2025-12-01", "member": "小妮", "is_participate": 1, "host": "", "review": "早起修改论文并提交，下午运动练臀腿；因兴奋晚睡，今日需完成论文格式修改与查重。"},
    {"date_str": "2025-12-01", "member": "鱼鱼", "is_participate": 1, "host": "", "review": "早起去母亲家吃早饭，处理工作中客户投诉与团队问题；晚上开会按自身想法解决难题，筹备开店事宜。"},
    {"date_str": "2025-12-01", "member": "浅夏", "is_participate": 1, "host": "", "review": "因药物反应卧床休息看书，母亲专程从怀化来看望；今日收拾妥当陪伴家人。"},

    {"date_str": "2025-12-02", "member": "浅夏", "is_participate": 1, "host": "浅夏", "review": "药物反应不适卧床休息，晚上短暂学习；感恩父母关怀与古籍带来的精神慰藉。"},
    {"date_str": "2025-12-02", "member": "Echo", "is_participate": 1, "host": "", "review": "生活规律，中午运动1小时，下班后看电影仍坚持读《芒格之道》与《牧羊少年漂流记》；不接受强加的价值观。"},
    {"date_str": "2025-12-02", "member": "七公主", "is_participate": 1, "host": "", "review": "整理11月复盘与生活记录，坚持读《资治通鉴》、健身与舞蹈课；和复盘搭子深度交流谈判技巧。"},
    {"date_str": "2025-12-02", "member": "光影", "is_participate": 1, "host": "", "review": "用13条美德记录，项目性能优化中思考本质；状态疲惫仍珍惜时间，思维偶有偷懒。"},
    {"date_str": "2025-12-02", "member": "小马哥", "is_participate": 1, "host": "", "review": "昨日休息调整，今日计划复盘上周工作、规划本周任务；推动家人一起学习修行。"},
    {"date_str": "2025-12-02", "member": "时成成", "is_participate": 1, "host": "", "review": "睡眠不足但效率较高，利用宝宝休息时间学习外语；用即兴表达哄睡宝宝，计划增加正念放松活动。"},

    {"date_str": "2025-12-03", "member": "鱼鱼", "is_participate": 1, "host": "莜面鱼鱼", "review": "上午因迟到状态不佳，下午参与销售技能分享；晚上照顾感冒小猫，学习宠物护理知识，今日专注当下做事。"},
    {"date_str": "2025-12-03", "member": "光影", "is_participate": 1, "host": "", "review": "坚持13条美德记录，勤勉学习冥想，晚餐节制；中午与同事沟通略上头，工作中需总结优化方法论。"},
    {"date_str": "2025-12-03", "member": "Sora", "is_participate": 1, "host": "", "review": "工作中遭遇部门利益冲突，协调客户资源时妥协部分利益达成共赢；晚上跳舞放松，今日计划读书。"},
    {"date_str": "2025-12-03", "member": "小马哥", "is_participate": 1, "host": "", "review": "整理家务与公共区域，清理书籍并预习出差要学的《天道酬德》；推动家族共同进步。"},
    {"date_str": "2025-12-03", "member": "Echo", "is_participate": 1, "host": "", "review": "生活规律，中午运动，晚上读《芒格之道》并做纸质笔记；领悟'只赚认知内的钱'。"},
    {"date_str": "2025-12-03", "member": "miss恩", "is_participate": 1, "host": "", "review": "本计划专注读书却沉迷小说，完成8个目标中的4个；反思开放性任务无需完美主义，今日用倒计时执行任务。"},
    {"date_str": "2025-12-03", "member": "时成成", "is_participate": 1, "host": "", "review": "帮婆婆切萝卜做咸菜，感受劳动的幸福感；调整作息同步宝宝睡眠，利用碎片时间学习。"},

    {"date_str": "2025-12-04", "member": "光影", "is_participate": 1, "host": "光影", "review": "面对陌生难题沉心研究，借助前期积累顺利解决；运动后学习网课倍感充实，闲谈略多需节制。"},
    {"date_str": "2025-12-04", "member": "miss恩", "is_participate": 1, "host": "", "review": "探索出'排名权重+清单排除'的选择方法论；昨日完成5个目标中的2个，今日严格按模板定计划。"},
    {"date_str": "2025-12-04", "member": "时成成", "is_participate": 1, "host": "", "review": "听《只管去做》并应用书中观点，制定五年愿景；感恩婆婆细心准备食材，今日计划多看此书。"},
    {"date_str": "2025-12-04", "member": "姜姜好", "is_participate": 1, "host": "", "review": "新部门任职，独立完成3份调研报告；晚上应酬中真诚沟通，今日跟进报告审批并计划读书。"},
    {"date_str": "2025-12-04", "member": "Echo", "is_participate": 1, "host": "", "review": "崴脚后居家看完《牧羊少年的奇幻之旅》；领悟'关注当下改善未来'，感恩宇宙的巧合安排。"},
    {"date_str": "2025-12-04", "member": "七公主", "is_participate": 1, "host": "", "review": "参观东北民俗博物馆，结合《资治通鉴》感受历史文化；图书馆感受学习氛围，今日完成项目管理课程。"},

    {"date_str": "2025-12-05", "member": "小妮", "is_participate": 1, "host": "小妮", "review": "完成论文阶段性上传，按截止日期优化标注与格式；熬夜赶工后需调整作息，今日整理AI工作。"},
    {"date_str": "2025-12-05", "member": "拈指花开", "is_participate": 1, "host": "", "review": "身体恢复后重启写字计划，整理字帖；计划春节前完成朋友委托的画作，学会忽略自身不完美。"},
    {"date_str": "2025-12-05", "member": "阳州", "is_participate": 1, "host": "", "review": "沟通部门工作分工获领导理解；计划寻找部门接替人员，处理外包司机加薪诉求，新办公环境舒适。"},
    {"date_str": "2025-12-05", "member": "明峻", "is_participate": 1, "host": "", "review": "上海出差时给同事和领导买早餐，融入集体；首次参加复盘，今日尝试保持该习惯。"},
    {"date_str": "2025-12-05", "member": "浅夏", "is_participate": 1, "host": "", "review": "阅读《沉思录》《道德经》思考美德与兵法的关系；图书馆让座获对方礼貌回应，今日继续攻读品德修养书籍。"},
    {"date_str": "2025-12-05", "member": "小马哥", "is_participate": 1, "host": "", "review": "首次上山修行，帮助寺庙整理仓库、修篱笆；领悟'实践出真知'，今日跟随住持学习。"},
    {"date_str": "2025-12-05", "member": "时成成", "is_participate": 1, "host": "", "review": "与姑姑和解，放下多年心结；制定五年愿景，今日计划完成辣萝卜腌制并多看书籍。"},

    {"date_str": "2025-12-06", "member": "阳州", "is_participate": 1, "host": "阳州", "review": "分享大厂复盘文化，昨日忙碌收尾新大楼搬迁事宜；坚持泡脚改善睡眠，今日计划慢跑运动。"},
    {"date_str": "2025-12-06", "member": "小妮", "is_participate": 1, "host": "", "review": "昨日休息调整，剪发、整理房间、早睡；周末安排社交活动，今日需完成运动打卡。"},
    {"date_str": "2025-12-06", "member": "光影", "is_participate": 1, "host": "", "review": "团建拔河坚持到最后，爬飞拉达时享受当下；领悟将困难转化为成就感，今日计划深度反思记录。"},
    {"date_str": "2025-12-06", "member": "七公主", "is_participate": 1, "host": "", "review": "坚持《资治通鉴》分享，完成汉朝皇帝核心事迹的小红书文案；取回刮擦的车，今日继续健身与读书。"},
    {"date_str": "2025-12-06", "member": "夏天", "is_participate": 1, "host": "", "review": "生病仍坚持备考心理统计学，发现速记卡APP辅助背诵；今日注重健康防护。"},
    {"date_str": "2025-12-06", "member": "miss恩", "is_participate": 1, "host": "", "review": "用番茄钟应对高难度任务，专注时间达标；今日计划接近预定目标，参加公园社交活动。"},
    {"date_str": "2025-12-06", "member": "浅夏", "is_participate": 1, "host": "", "review": "阅读《原则》探索自身思维原则；偏好抽象学术文章，减少碎片化信息摄入。"},

    {"date_str": "2025-11-30", "member": "光影", "is_participate": 1, "host": "光影", "review": "本月初偏佛系，月中读《原则》找回状态，月末巩固习惯；生活上养成运动后冥想习惯，尝试用富兰克林13条美德复盘；工作上关注专注与走神状态，总结“大胆假设、小心推理”高效方法论；解决眼睛不适问题，通过看电影宣泄情绪，自评8分。"},
    {"date_str": "2025-11-30", "member": "Isa", "is_participate": 1, "host": "", "review": "工作上从仅批评转向提建设性意见，缓解过度揽责的压力；生活上克服拖延，健身加入有氧改善焦虑，研读《原则》并参与相关复盘，参加财富流沙盘意识到资源梳理不足；情绪波动较大，需加强稳定性，将意识到的改进点落地，自评7分。"},
    {"date_str": "2025-11-30", "member": "浅夏", "is_participate": 1, "host": "", "review": "被外卖员撞后蜕变，20多天通过看书沉淀（《杀死一只知更鸟》《乔布斯传》《孙子兵法》等）修炼攻击力，从懵懂大学生成长为有智慧的善良人；探索自身思维原则，偏好抽象学术文章，减少碎片化信息摄入，自评10分。"},
    {"date_str": "2025-11-30", "member": "Sora", "is_participate": 1, "host": "", "review": "和搭子小金相处愉快，受其温柔提醒早睡；养成记录日常感动事的习惯，展会对接比利时客户，感受到行业欣欣向荣的自豪感；与Isa有共鸣（责任心强、讨好型人格），职场存在内耗，自评7分。"},
    {"date_str": "2025-11-30", "member": "小妍", "is_participate": 1, "host": "", "review": "以项目视角推进工作，避免精力跑偏；拆解商业模式和竞对获得灵感，计划捡回每日拆解习惯；大型事务先做SOP提升效率；完成工作增量计划框架，自媒体拆解3个竞对，下月计划形成拆解SOP并咨询AI相关框架。"},
    {"date_str": "2025-11-30", "member": "龙", "is_participate": 1, "host": "", "review": "践行输出与复盘循环，高效完成重点工作项目；给来京的父母做大餐，形象管理投入性价比高；11月减重十斤，坚持每日游泳1000米；相亲破圈参加集体活动，意识到找伴侣需关注综合品质，下月目标减重8斤、持续输出与阅读。"},
    {"date_str": "2025-11-30", "member": "李韫", "is_participate": 1, "host": "", "review": "从散步开始养成多个好习惯，在复盘群找到同行者；提前实现40岁独立写作梦想，定时定点定量写作坚持21天（写79页）；知行合一践行《反倦怠能量站》，提升外形、尝试健身房、朗读改善声音状态，规划文学播客，自评10分。"},
    {"date_str": "2025-11-30", "member": "夏天", "is_participate": 1, "host": "", "review": "逐小时记录时间并调整习惯，贴目标提升周计划达成率；召开2次家庭会议，3个欧卡线下个案实践成功；职称考试失利后调整心态，转行心理学相关学习（阅读2本书、多次咨询、考研复习心理统计学）；下月计划招募欧卡团体活动、推进考研复习等，自评9分。"},
    {"date_str": "2025-11-30", "member": "九月", "is_participate": 1, "host": "", "review": "养成早起、阅读习惯，自评7.5分；认为自身复盘不够系统，导致月复盘记忆模糊，后续需加强日常复盘记录。"},

    {"date_str": "2025-12-07", "member": "小妮", "is_participate": 1, "host": "小妮", "review": "主持周期性特别活动，围绕冲突解决、生活状态、习惯转化三大话题展开，组织多场景冲突演绎（上下级、婆媳、亲子、情感）；引导成员通过撒娇练习正向表达情感，总结冲突解决核心在于共情与需求平衡，收获是学会更深入探究对方隐性需求。"},
    {"date_str": "2025-12-07", "member": "miss恩", "is_participate": 1, "host": "", "review": "分享异地恋冲突处理方法，提出冲突解决五模式（强调、回避、妥协、迁就、合作），最优为合作共赢；尝试向浅夏撒娇邀约，收获是沟通前明确共同目标，不强迫对方，打电话比发消息更有效；用番茄钟应对高难度任务，提升专注力。"},
    {"date_str": "2025-12-07", "member": "时成成", "is_participate": 1, "host": "", "review": "分享母亲与婆婆因亲吻宝宝产生的矛盾，学到先肯定对方（“我知道你是为了宝宝好”）再解决问题；尝试向周周撒娇庆生，突破自身舒适区；收获是对家人需多耐心，避免过度提醒（隐性指责），正向表达需求更易被接受。"},
    {"date_str": "2025-12-07", "member": "阿龙", "is_participate": 1, "host": "", "review": "分享相亲经历，因不当消息导致关系降温，总结需构建“付出-正向反馈”模型，不提前贴标签，更关注内在品质（情绪稳定、原生家庭）；演绎文艺撒娇邀约，收获是肢体语言能反映好感，避免单向付出，引导对方适度投入。"},
    {"date_str": "2025-12-07", "member": "鱼鱼", "is_participate": 1, "host": "", "review": "多次作为冲突演绎被拒绝方，回应自然有分寸；参与撒娇练习，声音温柔反差萌；收获是解决矛盾要正向沟通、给对方台阶，不模棱两可，简单劳作能带来治愈感。"},
    {"date_str": "2025-12-07", "member": "光影", "is_participate": 1, "host": "", "review": "提出家庭关系中感性表达（撒娇、关怀）比理性分析更有效，“弱者道之动”以退为进；突破老干部人设念“撒娇八连”，演绎向时成成撒娇邀约；收获是切换角色，将工作理性转化为生活温和，让对方感受到重视。"},
    {"date_str": "2025-12-07", "member": "自由之花", "is_participate": 1, "host": "", "review": "分享与父亲的沟通矛盾（电瓶车充电安全、鸽子汤争议），收获是对家人要耐心+选对时机，可适当用“柔和威胁”（如“再唠叨就停工处理”）；尝试撒娇环节弃权，坦诚自己不擅长，真实不做作。"},
    {"date_str": "2025-12-07", "member": "阳州", "is_participate": 1, "host": "", "review": "演绎上下级冲突处理，强调职责清晰和制度规范的重要性；作为被撒娇方回应自然，后期尝试霸道总裁式撒娇邀约；收获是面对冲突要平常心，先识别需求再按规则解决，避免激化矛盾。"},
    {"date_str": "2025-12-07", "member": "Echo", "is_participate": 1, "host": "", "review": "分享异地朋友未回应“想聊天”的消息，自己生气几天但无正面冲突；收获是理性看待人际关系中的情绪，不强迫对方即时回应，专注自身生活节奏；参与复盘能量共振，感受到社群支持。"},
    {"date_str": "2025-12-07", "member": "浅夏", "is_participate": 1, "host": "", "review": "突破内向人设尝试撒娇邀约，虽生疏但完成挑战；分享阅读《沉思录》《道德经》的感悟，提出美德与兵法相辅相成；收获是识别对的人需要多经历、多相处，不能凭一次见面或直觉，减少碎片化信息摄入滋养大脑。"},
    # 新增日期数据示例（复制下面一行，修改日期、成员、主持人即可）
    # {"date_str": "2025-11-23", "member": "成员姓名", "is_participate": 1, "host": "", "review": ""},
    # 每个新日期只需在第一条记录填写主持人，其他成员留空
]

daily_speeches = {
"2025-12-07": {
        "小妮": "主持周期性特别活动，围绕冲突解决、生活状态、习惯转化三大话题展开，组织多场景冲突演绎（上下级、婆媳、亲子、情感）；引导成员通过撒娇练习正向表达情感，总结冲突解决核心在于共情与需求平衡，收获是学会更深入探究对方隐性需求。",
        "miss恩": "分享异地恋冲突处理方法，提出冲突解决五模式（强调、回避、妥协、迁就、合作），最优为合作共赢；尝试向浅夏撒娇邀约，收获是沟通前明确共同目标，不强迫对方，打电话比发消息更有效；用番茄钟应对高难度任务，提升专注力。",
        "时成成": "分享母亲与婆婆因亲吻宝宝产生的矛盾，学到先肯定对方（“我知道你是为了宝宝好”）再解决问题；尝试向阳州撒娇庆生，突破自身舒适区；收获是对家人需多耐心，避免过度提醒（隐性指责），正向表达需求更易被接受。",
        "阿龙": "分享相亲经历，因不当消息导致关系降温，总结需构建“付出-正向反馈”模型，不提前贴标签，更关注内在品质（情绪稳定、原生家庭）；演绎文艺撒娇邀约，收获是肢体语言能反映好感，避免单向付出，引导对方适度投入。",
        "鱼鱼": "多次作为冲突演绎被拒绝方，回应自然有分寸；参与撒娇练习，声音温柔反差萌；收获是解决矛盾要正向沟通、给对方台阶，不模棱两可，简单劳作能带来治愈感。",
        "光影": "提出家庭关系中感性表达（撒娇、关怀）比理性分析更有效，“弱者道之动”以退为进；突破老干部人设念“撒娇八连”，演绎向时成成撒娇邀约；收获是切换角色，将工作理性转化为生活温和，让对方感受到重视。",
        "自由之花": "分享与父亲的沟通矛盾（电瓶车充电安全、鸽子汤争议），收获是对家人要耐心+选对时机，可适当用“柔和威胁”（如“再唠叨就停工处理”）；尝试撒娇环节弃权，坦诚自己不擅长，真实不做作。",
        "李阳州": "演绎上下级冲突处理，强调职责清晰和制度规范的重要性；作为被撒娇方回应自然，后期尝试霸道总裁式撒娇邀约；收获是面对冲突要平常心，先识别需求再按规则解决，避免激化矛盾。",
        "Echo": "分享异地朋友未回应“想聊天”的消息，自己生气几天但无正面冲突；收获是理性看待人际关系中的情绪，不强迫对方即时回应，专注自身生活节奏；参与复盘能量共振，感受到社群支持。",
        "浅夏": "突破内向人设尝试撒娇邀约，虽生疏但完成挑战；收获是识别对的人需要多经历、多相处，不能凭一次见面或直觉。",
    },
    "2025-12-01": {
        "阿童": "彻底打扫房间、剪视频并交接宠物医生自媒体账号；创业阶段工作交接平稳，今日将与知识付费老师开启相关项目。",
        "光影": "用富兰克林13条美德复盘，晚餐稍过量、闲谈较多；坚持冥想与网课学习，优化项目性能时抓主要矛盾。",
        "李韫": "在陌生环境中营造安全感高效写作1小时；反思需提升饮食健康，今日计划去健身房。",
        "小马哥": "参加师傅线下学习，复习上周内容并聆听修行分享；领悟'福不可尽享'，推掉两场活动专注学习。",
        "小妮": "早起修改论文并提交，下午运动练臀腿；因兴奋晚睡，今日需完成论文格式修改与查重。",
        "鱼鱼": "早起去母亲家吃早饭，处理工作中客户投诉与团队问题；晚上开会按自身想法解决难题，筹备开店事宜。",
        "浅夏": "因药物反应卧床休息看书，母亲专程从怀化来看望；今日收拾妥当陪伴家人。"
    },
    "2025-12-02": {
        "浅夏": "药物反应不适卧床休息，晚上短暂学习；感恩父母关怀与古籍带来的精神慰藉。",
        "Echo": "生活规律，中午运动1小时，下班后看电影仍坚持读《芒格之道》与《牧羊少年漂流记》；不接受强加的价值观。",
        "七公主": "整理11月复盘与生活记录，坚持读《资治通鉴》、健身与舞蹈课；和复盘搭子深度交流谈判技巧。",
        "光影": "用13条美德记录，项目性能优化中思考本质；状态疲惫仍珍惜时间，思维偶有偷懒。",
        "小马哥": "昨日休息调整，今日计划复盘上周工作、规划本周任务；推动家人一起学习修行。",
        "时成成": "睡眠不足但效率较高，利用宝宝休息时间学习外语；用即兴表达哄睡宝宝，计划增加正念放松活动。"
    },
    "2025-12-03": {
        "鱼鱼": "上午因迟到状态不佳，下午参与销售技能分享；晚上照顾感冒小猫，学习宠物护理知识，今日专注当下做事。",
        "光影": "坚持13条美德记录，勤勉学习冥想，晚餐节制；中午与同事沟通略上头，工作中需总结优化方法论。",
        "Sora": "工作中遭遇部门利益冲突，协调客户资源时妥协部分利益达成共赢；晚上跳舞放松，今日计划读书。",
        "小马哥": "整理家务与公共区域，清理书籍并预习出差要学的《天道酬德》；推动家族共同进步。",
        "Echo": "生活规律，中午运动，晚上读《芒格之道》并做纸质笔记；领悟'只赚认知内的钱'。",
        "miss恩": "本计划专注读书却沉迷小说，完成8个目标中的4个；反思开放性任务无需完美主义，今日用倒计时执行任务。",
        "时成成": "帮婆婆切萝卜做咸菜，感受劳动的幸福感；调整作息同步宝宝睡眠，利用碎片时间学习。"
    },
    "2025-12-04": {
        "光影": "面对陌生难题沉心研究，借助前期积累顺利解决；运动后学习网课倍感充实，闲谈略多需节制。",
        "miss恩": "探索出'排名权重+清单排除'的选择方法论；昨日完成5个目标中的2个，今日严格按模板定计划。",
        "时成成": "听《只管去做》并应用书中观点，制定五年愿景；感恩婆婆细心准备食材，今日计划多看此书。",
        "姜姜好": "新部门任职，独立完成3份调研报告；晚上应酬中真诚沟通，今日跟进报告审批并计划读书。",
        "Echo": "崴脚后居家看完《牧羊少年的奇幻之旅》；领悟'关注当下改善未来'，感恩宇宙的巧合安排。",
        "七公主": "参观东北民俗博物馆，结合《资治通鉴》感受历史文化；图书馆感受学习氛围，今日完成项目管理课程。"
    },
    "2025-12-05": {
        "小妮": "完成论文阶段性上传，按截止日期优化标注与格式；熬夜赶工后需调整作息，今日整理AI工作。",
        "拈指花开": "身体恢复后重启写字计划，整理字帖；计划春节前完成朋友委托的画作，学会忽略自身不完美。",
        "阳州": "沟通部门工作分工获领导理解；计划寻找部门接替人员，处理外包司机加薪诉求，新办公环境舒适。",
        "明峻": "上海出差时给同事和领导买早餐，融入集体；首次参加复盘，今日尝试保持该习惯。",
        "浅夏": "阅读《沉思录》《道德经》思考美德与兵法的关系；图书馆让座获对方礼貌回应，今日继续攻读品德修养书籍。",
        "小马哥": "首次上山修行，帮助寺庙整理仓库、修篱笆；领悟'实践出真知'，今日跟随住持学习。",
        "时成成": "与姑姑和解，放下多年心结；制定五年愿景，今日计划完成辣萝卜腌制并多看书籍。"
    },
    "2025-12-06": {
        "阳州": "分享大厂复盘文化，昨日忙碌收尾新大楼搬迁事宜；坚持泡脚改善睡眠，今日计划慢跑运动。",
        "小妮": "昨日休息调整，剪发、整理房间、早睡；周末安排社交活动，今日需完成运动打卡。",
        "光影": "团建拔河坚持到最后，爬飞拉达时享受当下；领悟将困难转化为成就感，今日计划深度反思记录。",
        "七公主": "坚持《资治通鉴》分享，完成汉朝皇帝核心事迹的小红书文案；取回刮擦的车，今日继续健身与读书。",
        "夏天": "生病仍坚持备考心理统计学，发现速记卡APP辅助背诵；今日注重健康防护。",
        "miss恩": "用番茄钟应对高难度任务，专注时间达标；今日计划接近预定目标，参加公园社交活动。",
        "浅夏": "阅读《原则》探索自身思维原则；偏好抽象学术文章，减少碎片化信息摄入。"
    },


    "2025-11-30": {
        "匆匆": "休息话题：分享唱歌过度导致疲惫的经历，提出 “休息需讲究度，遵循中庸之道”。理想 vs 现实话题：提提到同事疫情期间辞职追抖音理想失败的案例，认为无兜底时不应一味追求理想；感慨普通人易被现实束缚，好奇成功者的长期布局。",
        "鱼鱼": "好好休息：核心是把控工作与生活节奏，提高专注力；休息时需全身心投入，避免睡前玩手机，注重自律。内耗应对：认为减少内耗的关键是 “知行合一”，想明白目标后直接行动，无法完全避免但可有效减少。",
        "二月": "好好休息：身体会发出疲惫信号（如困、不想动），应及时响应，不被工作、学习或手机娱乐牵绊，让身体充分休息。心与脑的关系：引用站桩老师的观点，认为生活中常被大脑牵引，发心端正能带来充足能量，支撑应对困难；换工作后体会到正向发心对工作热情的推动作用。",
        "光影": "好好休息：大脑负荷超限时（如紧张场景、高频社交后）易头疼，需通过 “转移注意力”（如户外散步）或 “减少认知负荷”（如冥想）休息，避免碎片化刷手机。补充最低成本的休息方式是切换注意力，冥想可降低大脑负荷、练习注意力控制。",
        "时成成": "好好休息：休息不止睡觉，还包括接纳情绪；推荐户外散步（10-20 分钟），感受阳光和风，观察植物，能忘记焦虑，有效放松脑力。",
        "小马哥": "好好休息：休息是 “换脑” 过程，可通过娱乐短视频、小品等获取情绪价值，让大脑暂停信息消化；超负荷时需补充营养、停止消耗，快速缓解疲劳。锋芒毕露 vs 韬光养晦：分阶段、分场合选择：锋芒毕露易带贬义，过早显露可能错失良机，建议先韬光养晦、沉淀知识能量，再适时展示价值；两者不矛盾，需取舍有度、顺势而为。"
                  "理想 vs 现实：创业需先修行，明确人生使命，以 “利他” 为核心发大愿，积累福报，再成就事业；反对一味追逐利益，强调德行与愿力的重要性。理想与现实是多选题：先解决生存问题（吃饱穿暖），再追求理想（可大可小），避免脱离现实空谈理想，也不因只重生存而停滞进步。",
        "李理": "好好休息：休息分身体休息和心神休息，城市人易被外界信息轰炸导致 “心累”；体力劳动或运动能让思维停摆，减少内耗，真正放松心神。理想 vs 现实：支持 “厚德载物”，认为商业成功或人生成就的核心是德行与福报，而非单纯的能力超群；生存是理想的基础，有经济兜底后再追求理想更稳妥。",
        "阿童": "好好休息：休息分两种 —— 大脑放松（抛却工作、做喜欢的事）和阶段性休息（增加午睡、冥想、看电影、旅游等）；建议日常工作中制定休息时间，完成阶段性工作后给予休息奖励。",
        "浅夏":"好好休息：从神经科学角度提出：深度睡眠、冥想（闭眼放空）、运动（促进多巴胺分泌、平稳血糖）能恢复精力；少吃辛辣刺激食物、少看刺激信息，保持情绪平稳，高效分配精力。锋芒毕露 vs 韬光养晦：支持先韬光养晦沉淀自己，再适时施展才华；锋芒毕露的核心是实践落地、提升自我，而非单纯展示，还可能唤醒他人的积极品质。"
               "理想 vs 现实：普通人需先适应社会、解决生存问题，再发展自我；理想需依托现实，避免脱离实际的空想。自身虽受学校老师打压式教育影响，但通过图书馆独处坚定理想信念，追求高尚品德，虽理想不明确，但明确喜欢的方向并稳步前进。被外卖员撞后蜕变，20多天通过看书沉淀（《杀死一只知更鸟》《乔布斯传》《孙子兵法》等）修炼攻击力，从懵懂大学生成长为有智慧的善良人；探索自身思维原则，偏好抽象学术文章，减少碎片化信息摄入。",
        "姜姜好": "锋芒毕露 vs 韬光养晦：分人生阶段选择 —— 刚入职场时上进积极，自然显露朝气；有经验后更注重稳定内核，不以外界评价为导向；有家庭后兼顾责任与自我，顺势而为、恰如其时做事。理想 vs 现实：普通人需先适应社会、解决生存问题，再发展自我；理想需依托现实，避免脱离实际的空想。企业或个人发展应秉持长期主义，如可口可乐深耕客户长期需求，反对脑白金式短期逐利、昙花一现。",
        "阳州": "锋芒毕露 vs 韬光养晦：倾向 “锋芒毕露”，前提是做事正向、符合价值观：能吸引同频的人，凝聚力量共同做事；自媒体时代连接成本低，易获得资源和机会；职场中适度显露才能（如营销竞赛中脱颖而出），能被关注获得更多发展机遇；注意分寸，避免不分场合过度曝光情绪或工作内容。",
        "七公主": "理想 vs 现实：核心是 “既要仰望星空，又要脚踏实地”，平衡理想与现实：理想提供人生方向和动力，现实是践行理想的基础，缺一不可；宏大理想需拆解为三年计划、五年计划，再细化为可落地的小目标，通过践行实现；呼应王阳明 “知行合一”，强调 “知是行之始，行是知之成”，避免空想或盲目行动。",
        "Isa": "工作上从仅批评转向提建设性意见，缓解过度揽责的压力；生活上克服拖延，健身加入有氧改善焦虑，研读《原则》并参与相关复盘，参加财富流沙盘意识到资源梳理不足；情绪波动较大，需加强稳定性，将意识到的改进点落地。",
        "Sora": "和搭子小金相处愉快，受其温柔提醒早睡；养成记录日常感动事的习惯，展会对接比利时客户，感受到行业欣欣向荣的自豪感；与Isa有共鸣（责任心强、讨好型人格），职场存在内耗，在探索人生目标与价值感。",
        "小妍": "以项目视角推进工作，避免精力跑偏；拆解商业模式和竞对获得灵感，计划捡回每日拆解习惯；大型事务先做SOP提升效率；完成工作增量计划框架，自媒体拆解3个竞对，下月计划形成拆解SOP并咨询AI相关框架。",
        "阿龙": "践行输出与复盘循环，高效完成重点工作项目；给来京的父母做大餐，形象管理投入性价比高；11月减重十斤，坚持每日游泳1000米；相亲破圈参加集体活动，意识到找伴侣需关注综合品质，下月目标减重8斤、持续输出与阅读。",
        "李韫": "从散步开始养成多个好习惯，在复盘群找到同行者；提前实现40岁独立写作梦想，定时定点定量写作坚持21天（写79页）；知行合一践行《反倦怠能量站》，提升外形、尝试健身房、朗读改善声音状态，规划文学播客。",
        "夏天": "逐小时记录时间并调整习惯，贴目标提升周计划达成率；召开2次家庭会议，3个欧卡线下个案实践成功；职称考试失利后调整心态，转行心理学相关学习（阅读2本书、多次咨询、考研复习心理统计学）；下月计划招募欧卡团体活动、推进考研复习等。",
        "九月": "养成早起、阅读习惯，自评7.5分；认为自身复盘不够系统，导致月复盘记忆模糊，后续需加强日常复盘记录。"
    },

    "2025-11-29": {
        "阳州": "筹备新分行迁址，1天内完成金融许可证、营业执照加急办理，凌晨调试电路网络，今天10点新址开业。",
        "光影": "工作时能快速切换任务状态；健身房帮他人避免卧推危险，意外结识爱运动+爱阅读的同好；反思记录不足。",
        "自由之花": "从英语组转道德与法制组，将读书会形式融入课堂，带动同事读书，用书中方法帮同事梳理情绪。",
        "浅夏": "专注学术研究理清混杂概念；读《乔布斯传》受启发；因室友熬夜打游戏纠结是否补觉。",
        "小马哥": "读书会新增书法课程（读书+临摹+写祝福语），帮助大家静心；反思时间管理不足。",
        "小妮": "论文修改遇挫，按老师要求用sparse分析法但结果不符，计划先明确思路再推进，避免无用功。",
        "时成成": "靠搭子监督完成英语学习，用番茄钟提升效率；观察宝宝作息找到高效学习时段。",
        "夏天": "筹备转行心理咨询，独自承担班级工作+生病仍坚持；学习人本主义课程，记录梦境助力自我探索。"
    },
    "2025-11-28": {
        "小马哥": "杭州学习后休息调整，推进读书会+演讲俱乐部筹备；反思执行力不足，计划提升能量聚焦目标。",
        "光影": "工作中抓主要矛盾，优先解决常用场景问题；坚持运动+冥想；反思吃饭刷手机的连锁反应。",
        "鱼鱼": "整理高效能习惯（积极主动、以终为始等）；和朋友看初雪；反思熬夜玩手机，计划规律作息。",
        "花满天": "拒绝不合理工作任务，与领导沟通达成方案；调整心态不因繁杂事务影响睡眠。",
        "时成成": "靠搭子监督完成学习，用番茄钟提升效率；观察宝宝作息找到高效时段。",
        "阳州": "新分行筹备忙至深夜，从目标倒推行动；计划在校友会组织读书分享会。"
    },
    "2025-11-27": {
        "鱼鱼": "研究毛选矛盾论与实践论，和领导沟通工作价值达成调整；计划开新店，引导同事开展早会；反思熬夜未读书。",
        "阿童": "推进宠物医院IP项目，将博主朋友的狗作为素材提升流量；开启线上自媒体读书会（每周一20:30）；因新项目开启暂时封闭自己调整状态。",
        "小妮": "拿下大额长期合作，团队全员学习AI技术；论文修改思路明确，加班推进；强调AI时代3年窗口期，需快速落地形成壁垒。",
        "光影": "按《高效能人士的七个习惯》复盘，优先做重要不紧急的事（Python学习、方法论搭建）；工作中简化代码系统，避免冗余；晚上少看影视剧，完成网课学习。",
        "二月": "公司EOP活动成功，主管及时赋能支持；参与线下演讲俱乐部锻炼表达；从抗拒主持转变为期待尝试主持。",
        "李韫": "参加胃部疾病分享会，了解“梅核气”病症；反思熬夜等不良生活习惯；建群共读《远离疾病》，突破健康认知。",
        "花满天": "拒绝不合理工作任务，与领导沟通达成合适方案；调整心态，不因繁杂事务影响睡眠；反思人际关系调节不足。",
        "晴天": "考导游证遇挫（刷4000题未从题库出），改以学习文史地知识的心态备考；考取培训师证，题库难度较低；感恩与大家相遇，享受偶尔复盘交流。"
    },
    "2025-11-26": {
        "光影": "工作中做长期受益的事（规范代码文档）；反思对工作热情下降，计划制定新目标、和同事交流提升效率；晚上少看影视剧，完成网课学习。",
        "李韫": "早起早读、下午写作形成身体记忆，无需强迫；情绪波动时用番茄钟调整，仍能完成任务；希望运动也养成身体记忆。",
        "时成成": "带宝宝复诊遭医生指责，受母亲负能量影响情绪；反思情绪敏感，计划建立情绪屏障；学习中断，选择复习旧知识。",
        "二月": "普拉提课程优惠活动引发纠结，最终因运动+社交需求报名；反思决策时需综合价格、时间成本。",
        "鱼鱼": "骨折复查结果良好，感悟“发现问题立即解决，不延迟满足”；看曾国藩纪录片，记录自律、谨言慎行等观点；参加每日一善群，提醒自己多做善事。",
        "七公主": "坚持读《资治通鉴》、健身、发自媒体（底层习惯+读书笔记）；车刮蹭后反思开车需慢速安全；计划早睡、完成课件开发。",
        "小马哥": "杭州参加3天2晚学习，小组PK获第三名；课程干货多，平台门槛低，计划直播时推广相关产品；提醒报课需考虑时间、距离成本，避免浪费。"
    },
    "2025-11-25": {
        "阿成": "处理周末积累的工作，优化工作规划；阅读《我不擅长的生活》第一章；反思熬夜玩游戏，计划早睡。",
        "鱼鱼": "上午培训员工（抖音IP打造、招聘/销售技巧），下午参加读书会；晚上请朋友吃饭收到鲜花；感悟“学而未觉的耐受力”，接纳成长节奏。",
        "小妮": "工作上完成历史性合作突破，论文修改进度超预期；用AI梳理家庭情绪问题，用番茄钟缓解焦虑；坚持运动打卡活动，影响200+人。",
        "光影": "状态不佳时调整预期、明确主要矛盾；工作中高效沟通+协作，发挥双方优势（自己用代码定位数据，对方做业务分析）；坚持冥想+网课学习，分享“我想要”替代“我得”的习惯养成法。",
        "七公主": "坚持读《资治通鉴》、健身、发自媒体（小红书分享底层习惯与读书笔记）；车刮蹭后反思开车需慢速；计划早睡、完成课件开发。"
    },
    "2025-11-24": {
        "小妮": "上午陪伴家人、收拾屋子，下午去咖啡厅修改论文（按老师意见优化逻辑）；晚上冥想早睡，受早睡冥想群案例启发坚持早睡。",
        "鱼鱼": "泡澡桶漏水淹家，朋友深夜帮忙收拾；感悟“真诚需对合适的人，吃亏是认知不足的成长机会，幸福是所拥有的能带来快乐”；参加早复盘分享。",
        "陈庚": "昨天的关键词是惊喜，分享生活中的惊喜片段。",
        "阿成": "周末和朋友爬1084米高山，磨练意志；参加复盘发现工作规划不足，计划改进；未完成阅读目标，计划今日补读《我不擅长的生活》第一章。",
        "Sora": "周末休息，看时尚纪录片（了解LV、Coach等品牌运作及刚果地区时尚执念）和电视剧《余生有涯》（女性性侵后维权）；感悟刚果地区对文明的渴望，敬佩剧中女性的维权勇气。",
        "时成成": "尝试让爸爸亲近宝宝，发现宝宝开心；反思过度玩手机，计划减少手机时长，陪娃时不玩手机；早上利用复盘前时间读书，替代玩手机。"
    }
    # 其他日期的成员发言按此格式补充...
}