# ---------------------- 【每日数据录入区】（原有数据不变）----------------------
DAILY_DATA = [
    # 本周六（2025-11-22）：主持人李韫
    {"date_str": "2025-11-22", "member": "陈庚", "is_participate": 1, "host": "李韫", "review": ""},
    {"date_str": "2025-11-22", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "自由之花", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "李韫", "is_participate": 1, "host": "", "review": ""},  # 主持人自身也在参与列表
    # 本周五（2025-11-21）：主持人小妮
    {"date_str": "2025-11-21", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-21", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    # 本周四（2025-11-20）：主持人小马哥
    {"date_str": "2025-11-20", "member": "陈庚", "is_participate": 1, "host": "小马哥", "review": ""},
    {"date_str": "2025-11-20", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    # 本周三（2025-11-19）：主持人浅夏
    {"date_str": "2025-11-19", "member": "光影", "is_participate": 1, "host": "浅夏", "review": ""},
    {"date_str": "2025-11-19", "member": "sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    # 本周二（2025-11-18）：主持人光影
    {"date_str": "2025-11-18", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-18", "member": "sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    # 本周一（2025-11-17）：主持人时成成
    {"date_str": "2025-11-17", "member": "光影", "is_participate": 1, "host": "时成成", "review": ""},
    {"date_str": "2025-11-17", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "小妮", "is_participate": 1, "host": "", "review": ""},

    # 11月16日（周日）：主持人光影
    {"date_str": "2025-11-16", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-16", "member": "桃子", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "王永涛", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "鱼大爷", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},

    # 11月15日（周六）：主持人阳州
    {"date_str": "2025-11-15", "member": "鱼鱼", "is_participate": 1, "host": "阳州", "review": ""},
    {"date_str": "2025-11-15", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-15", "member": "光影", "is_participate": 1, "host": "", "review": ""},

    # 11月14日（周五）：主持人miss恩
    {"date_str": "2025-11-14", "member": "光影", "is_participate": 1, "host": "miss恩", "review": ""},
    {"date_str": "2025-11-14", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月13日（周四）：主持人小马哥
    {"date_str": "2025-11-13", "member": "光影", "is_participate": 1, "host": "小马哥", "review": ""},
    {"date_str": "2025-11-13", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "团子", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "小金", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月12日（周三）：主持人花满天
    {"date_str": "2025-11-12", "member": "光影", "is_participate": 1, "host": "花满天", "review": ""},
    {"date_str": "2025-11-12", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月11日（周二）：主持人光影
    {"date_str": "2025-11-11", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-11", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11月10日（周一）：主持人小妮
    {"date_str": "2025-11-10", "member": "阿成", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-10", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "阿童", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "曾律师", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},

# 1号（2025-11-01）：主持人小妮
    {"date_str": "2025-11-01", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-01", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 2号（2025-11-02）：主持人小妮
    {"date_str": "2025-11-02", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-02", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-02", "member": "Betty", "is_participate": 1, "host": "", "review": ""},

    # 3号（2025-11-03）：主持人光影
    {"date_str": "2025-11-03", "member": "莫非", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-03", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "阿童", "is_participate": 1, "host": "", "review": ""},

    # 4号（2025-11-04）：主持人小妮
    {"date_str": "2025-11-04", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-04", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "李韫", "is_participate": 1, "host": "", "review": ""},

    # 5号（2025-11-05）：主持人小妮
    {"date_str": "2025-11-05", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-05", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},

    # 6号（2025-11-06）：主持人小妮
    {"date_str": "2025-11-06", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-06", "member": "桃桃", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},

    # 7号（2025-11-07）：主持人光影
    {"date_str": "2025-11-07", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-07", "member": "小妍", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "桃桃", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "小金", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},

    # 8号（2025-11-08）：主持人小妮
    {"date_str": "2025-11-08", "member": "光影", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-08", "member": "Libby", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "miss恩", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},

    # 9号（2025-11-09）：主持人光影
    {"date_str": "2025-11-09", "member": "Betty", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-09", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "白了个白", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "拈指花开", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "自由之花", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阿信", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "九月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11-09（主持人光影）
    {"date_str": "2025-11-09", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-09", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "九月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "Isa", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "Betty", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小金", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-09", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11-16（主持人光影）
    {"date_str": "2025-11-16", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-16", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "Betty", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "九月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "阿龙", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "Isa", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "小妮", "is_participate": 1, "host": "", "review": ""},

    {"date_str": "2025-11-01", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-01", "member": "平平", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-03", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-04", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-05", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-06", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "平平", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-07", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-08", "member": "平平", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-10", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-11", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-12", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-13", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-14", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-16", "member": "桃子", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-17", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-18", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-19", "member": "echo", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-20", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-21", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-22", "member": "夏天", "is_participate": 1, "host": "", "review": ""},

    # 11-23（主持人miss恩）
    {"date_str": "2025-11-23", "member": "miss恩", "is_participate": 1, "host": "miss恩", "review": ""},
    {"date_str": "2025-11-23", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "夏天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "匆匆", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-23", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},

    # 11月24日（主持人：小妮）
    {"date_str": "2025-11-24", "member": "小妮", "is_participate": 1, "host": "小妮", "review": ""},
    {"date_str": "2025-11-24", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "陈庚", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "阿成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "Sora", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-24", "member": "时成成", "is_participate": 1, "host": "", "review": ""},

    # 11月25日（主持人：阿成）
    {"date_str": "2025-11-25", "member": "阿成", "is_participate": 1, "host": "阿成", "review": ""},
    {"date_str": "2025-11-25", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-25", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-25", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-25", "member": "七公主", "is_participate": 1, "host": "", "review": ""},

    # 11月26日（主持人：光影）
    {"date_str": "2025-11-26", "member": "光影", "is_participate": 1, "host": "光影", "review": ""},
    {"date_str": "2025-11-26", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "七公主", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-26", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},

    # 11月27日（主持人：鱼鱼）
    {"date_str": "2025-11-27", "member": "鱼鱼", "is_participate": 1, "host": "鱼鱼", "review": ""},
    {"date_str": "2025-11-27", "member": "阿童", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "李韫", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-27", "member": "晴天", "is_participate": 1, "host": "", "review": ""},

    # 11月28日（主持人：小马哥）
    {"date_str": "2025-11-28", "member": "小马哥", "is_participate": 1, "host": "小马哥", "review": ""},
    {"date_str": "2025-11-28", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "花满天", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-28", "member": "阳州", "is_participate": 1, "host": "", "review": ""},

    # 11月29日（主持人：阳州）
    {"date_str": "2025-11-29", "member": "阳州", "is_participate": 1, "host": "阳州", "review": ""},
    {"date_str": "2025-11-29", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "自由之花", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "小妮", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-29", "member": "夏天", "is_participate": 1, "host": "", "review": ""},

    # 11月30日（主持人：匆匆）
    {"date_str": "2025-11-30", "member": "匆匆", "is_participate": 1, "host": "匆匆", "review": ""},
    {"date_str": "2025-11-30", "member": "鱼鱼", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "二月", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "光影", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "时成成", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "小马哥", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "李理", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "阿童", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "浅夏", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "姜姜好", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "阳州", "is_participate": 1, "host": "", "review": ""},
    {"date_str": "2025-11-30", "member": "七公主", "is_participate": 1, "host": "", "review": ""},

    # 新增日期数据示例（复制下面一行，修改日期、成员、主持人即可）
    # {"date_str": "2025-11-23", "member": "成员姓名", "is_participate": 1, "host": "", "review": ""},
    # 每个新日期只需在第一条记录填写主持人，其他成员留空
]

daily_speeches = {
    "2025-11-30": {
        "匆匆": "休息话题：分享唱歌过度导致疲惫的经历，提出 “休息需讲究度，遵循中庸之道”。理想 vs 现实话题：提提到同事疫情期间辞职追抖音理想失败的案例，认为无兜底时不应一味追求理想；感慨普通人易被现实束缚，好奇成功者的长期布局。",
        "鱼鱼": "好好休息：核心是把控工作与生活节奏，提高专注力；休息时需全身心投入，避免睡前玩手机，注重自律。内耗应对：认为减少内耗的关键是 “知行合一”，想明白目标后直接行动，无法完全避免但可有效减少。",
        "二月": "好好休息：身体会发出疲惫信号（如困、不想动），应及时响应，不被工作、学习或手机娱乐牵绊，让身体充分休息。心与脑的关系：引用站桩老师的观点，认为生活中常被大脑牵引，发心端正能带来充足能量，支撑应对困难；换工作后体会到正向发心对工作热情的推动作用。",
        "光影": "好好休息：大脑负荷超限时（如紧张场景、高频社交后）易头疼，需通过 “转移注意力”（如户外散步）或 “减少认知负荷”（如冥想）休息，避免碎片化刷手机。补充最低成本的休息方式是切换注意力，冥想可降低大脑负荷、练习注意力控制。",
        "时成成": "好好休息：休息不止睡觉，还包括接纳情绪；推荐户外散步（10-20 分钟），感受阳光和风，观察植物，能忘记焦虑，有效放松脑力。",
        "小马哥": "好好休息：休息是 “换脑” 过程，可通过娱乐短视频、小品等获取情绪价值，让大脑暂停信息消化；超负荷时需补充营养、停止消耗，快速缓解疲劳。锋芒毕露 vs 韬光养晦：分阶段、分场合选择：锋芒毕露易带贬义，过早显露可能错失良机，建议先韬光养晦、沉淀知识能量，再适时展示价值；两者不矛盾，需取舍有度、顺势而为。"
                  "理想 vs 现实：创业需先修行，明确人生使命，以 “利他” 为核心发大愿，积累福报，再成就事业；反对一味追逐利益，强调德行与愿力的重要性。理想与现实是多选题：先解决生存问题（吃饱穿暖），再追求理想（可大可小），避免脱离现实空谈理想，也不因只重生存而停滞进步。",
        "李理": "好好休息：休息分身体休息和心神休息，城市人易被外界信息轰炸导致 “心累”；体力劳动或运动能让思维停摆，减少内耗，真正放松心神。理想 vs 现实：支持 “厚德载物”，认为商业成功或人生成就的核心是德行与福报，而非单纯的能力超群；生存是理想的基础，有经济兜底后再追求理想更稳妥。",
        "阿童": "好好休息：休息分两种 —— 大脑放松（抛却工作、做喜欢的事）和阶段性休息（增加午睡、冥想、看电影、旅游等）；建议日常工作中制定休息时间，完成阶段性工作后给予休息奖励。",
        "浅夏":"好好休息：从神经科学角度提出：深度睡眠、冥想（闭眼放空）、运动（促进多巴胺分泌、平稳血糖）能恢复精力；少吃辛辣刺激食物、少看刺激信息，保持情绪平稳，高效分配精力。锋芒毕露 vs 韬光养晦：支持先韬光养晦沉淀自己，再适时施展才华；锋芒毕露的核心是实践落地、提升自我，而非单纯展示，还可能唤醒他人的积极品质。"
               "理想 vs 现实：普通人需先适应社会、解决生存问题，再发展自我；理想需依托现实，避免脱离实际的空想。自身虽受学校老师打压式教育影响，但通过图书馆独处坚定理想信念，追求高尚品德，虽理想不明确，但明确喜欢的方向并稳步前进。",
        "姜姜好": "锋芒毕露 vs 韬光养晦：分人生阶段选择 —— 刚入职场时上进积极，自然显露朝气；有经验后更注重稳定内核，不以外界评价为导向；有家庭后兼顾责任与自我，顺势而为、恰如其时做事。理想 vs 现实：普通人需先适应社会、解决生存问题，再发展自我；理想需依托现实，避免脱离实际的空想。企业或个人发展应秉持长期主义，如可口可乐深耕客户长期需求，反对脑白金式短期逐利、昙花一现。",
        "阳州": "锋芒毕露 vs 韬光养晦：倾向 “锋芒毕露”，前提是做事正向、符合价值观：能吸引同频的人，凝聚力量共同做事；自媒体时代连接成本低，易获得资源和机会；职场中适度显露才能（如营销竞赛中脱颖而出），能被关注获得更多发展机遇；注意分寸，避免不分场合过度曝光情绪或工作内容。",
        "七公主": "理想 vs 现实：核心是 “既要仰望星空，又要脚踏实地”，平衡理想与现实：理想提供人生方向和动力，现实是践行理想的基础，缺一不可；宏大理想需拆解为三年计划、五年计划，再细化为可落地的小目标，通过践行实现；呼应王阳明 “知行合一”，强调 “知是行之始，行是知之成”，避免空想或盲目行动。",
    },

    "2025-11-29": {
        "阳州": "筹备新分行迁址，1天内完成金融许可证、营业执照加急办理，凌晨调试电路网络，今天10点新址开业。",
        "光影": "工作时能快速切换任务状态；健身房帮他人避免卧推危险，意外结识爱运动+爱阅读的同好；反思记录不足。",
        "自由之花": "从英语组转道德与法制组，将读书会形式融入课堂，带动同事读书，用书中方法帮同事梳理情绪。",
        "浅夏": "专注学术研究理清混杂概念；读《乔布斯传》受启发；因室友熬夜打游戏纠结是否补觉。",
        "小马哥": "读书会新增书法课程（读书+临摹+写祝福语），帮助大家静心；反思时间管理不足。",
        "小妮": "论文修改遇挫，按老师要求用sparse分析法但结果不符，计划先明确思路再推进，避免无用功。",
        "时成成": "靠搭子监督完成英语学习，用番茄钟提升效率；观察宝宝作息找到高效学习时段。",
        "夏天": "筹备转行心理咨询，独自承担班级工作+生病仍坚持；学习人本主义课程，记录梦境助力自我探索。"
    },
    "2025-11-28": {
        "小马哥": "杭州学习后休息调整，推进读书会+演讲俱乐部筹备；反思执行力不足，计划提升能量聚焦目标。",
        "光影": "工作中抓主要矛盾，优先解决常用场景问题；坚持运动+冥想；反思吃饭刷手机的连锁反应。",
        "鱼鱼": "整理高效能习惯（积极主动、以终为始等）；和朋友看初雪；反思熬夜玩手机，计划规律作息。",
        "花满天": "拒绝不合理工作任务，与领导沟通达成方案；调整心态不因繁杂事务影响睡眠。",
        "时成成": "靠搭子监督完成学习，用番茄钟提升效率；观察宝宝作息找到高效时段。",
        "阳州": "新分行筹备忙至深夜，从目标倒推行动；计划在校友会组织读书分享会。"
    },
    "2025-11-27": {
        "鱼鱼": "研究毛选矛盾论与实践论，和领导沟通工作价值达成调整；计划开新店，引导同事开展早会；反思熬夜未读书。",
        "阿童": "推进宠物医院IP项目，将博主朋友的狗作为素材提升流量；开启线上自媒体读书会（每周一20:30）；因新项目开启暂时封闭自己调整状态。",
        "小妮": "拿下大额长期合作，团队全员学习AI技术；论文修改思路明确，加班推进；强调AI时代3年窗口期，需快速落地形成壁垒。",
        "光影": "按《高效能人士的七个习惯》复盘，优先做重要不紧急的事（Python学习、方法论搭建）；工作中简化代码系统，避免冗余；晚上少看影视剧，完成网课学习。",
        "二月": "公司EOP活动成功，主管及时赋能支持；参与线下演讲俱乐部锻炼表达；从抗拒主持转变为期待尝试主持。",
        "李韫": "参加胃部疾病分享会，了解“梅核气”病症；反思熬夜等不良生活习惯；建群共读《远离疾病》，突破健康认知。",
        "花满天": "拒绝不合理工作任务，与领导沟通达成合适方案；调整心态，不因繁杂事务影响睡眠；反思人际关系调节不足。",
        "晴天": "考导游证遇挫（刷4000题未从题库出），改以学习文史地知识的心态备考；考取培训师证，题库难度较低；感恩与大家相遇，享受偶尔复盘交流。"
    },
    "2025-11-26": {
        "光影": "工作中做长期受益的事（规范代码文档）；反思对工作热情下降，计划制定新目标、和同事交流提升效率；晚上少看影视剧，完成网课学习。",
        "李韫": "早起早读、下午写作形成身体记忆，无需强迫；情绪波动时用番茄钟调整，仍能完成任务；希望运动也养成身体记忆。",
        "时成成": "带宝宝复诊遭医生指责，受母亲负能量影响情绪；反思情绪敏感，计划建立情绪屏障；学习中断，选择复习旧知识。",
        "二月": "普拉提课程优惠活动引发纠结，最终因运动+社交需求报名；反思决策时需综合价格、时间成本。",
        "鱼鱼": "骨折复查结果良好，感悟“发现问题立即解决，不延迟满足”；看曾国藩纪录片，记录自律、谨言慎行等观点；参加每日一善群，提醒自己多做善事。",
        "七公主": "坚持读《资治通鉴》、健身、发自媒体（底层习惯+读书笔记）；车刮蹭后反思开车需慢速安全；计划早睡、完成课件开发。",
        "小马哥": "杭州参加3天2晚学习，小组PK获第三名；课程干货多，平台门槛低，计划直播时推广相关产品；提醒报课需考虑时间、距离成本，避免浪费。"
    },
    "2025-11-25": {
        "阿成": "处理周末积累的工作，优化工作规划；阅读《我不擅长的生活》第一章；反思熬夜玩游戏，计划早睡。",
        "鱼鱼": "上午培训员工（抖音IP打造、招聘/销售技巧），下午参加读书会；晚上请朋友吃饭收到鲜花；感悟“学而未觉的耐受力”，接纳成长节奏。",
        "小妮": "工作上完成历史性合作突破，论文修改进度超预期；用AI梳理家庭情绪问题，用番茄钟缓解焦虑；坚持运动打卡活动，影响200+人。",
        "光影": "状态不佳时调整预期、明确主要矛盾；工作中高效沟通+协作，发挥双方优势（自己用代码定位数据，对方做业务分析）；坚持冥想+网课学习，分享“我想要”替代“我得”的习惯养成法。",
        "七公主": "坚持读《资治通鉴》、健身、发自媒体（小红书分享底层习惯与读书笔记）；车刮蹭后反思开车需慢速；计划早睡、完成课件开发。"
    },
    "2025-11-24": {
        "小妮": "上午陪伴家人、收拾屋子，下午去咖啡厅修改论文（按老师意见优化逻辑）；晚上冥想早睡，受早睡冥想群案例启发坚持早睡。",
        "鱼鱼": "泡澡桶漏水淹家，朋友深夜帮忙收拾；感悟“真诚需对合适的人，吃亏是认知不足的成长机会，幸福是所拥有的能带来快乐”；参加早复盘分享。",
        "陈庚": "昨天的关键词是惊喜，分享生活中的惊喜片段。",
        "阿成": "周末和朋友爬1084米高山，磨练意志；参加复盘发现工作规划不足，计划改进；未完成阅读目标，计划今日补读《我不擅长的生活》第一章。",
        "Sora": "周末休息，看时尚纪录片（了解LV、Coach等品牌运作及刚果地区时尚执念）和电视剧《余生有涯》（女性性侵后维权）；感悟刚果地区对文明的渴望，敬佩剧中女性的维权勇气。",
        "时成成": "尝试让爸爸亲近宝宝，发现宝宝开心；反思过度玩手机，计划减少手机时长，陪娃时不玩手机；早上利用复盘前时间读书，替代玩手机。"
    }
    # 其他日期的成员发言按此格式补充...
}